import { Button, Card, Section, StatusTag } from "@prototype/design-system";
import { PrototypeIcon } from "@prototype/icons";
import { getPrototypeView, PrototypePanel, PrototypeState } from "@prototype/runtime";

const appName = import.meta.env.VITE_APP_NAME || "Com Design Prototype";

export function App() {
  const view = getPrototypeView();
  return <div className="min-h-[100dvh] bg-[var(--color-background)] text-[var(--color-text-primary)]"><header className="sticky top-0 z-20 border-b border-[var(--color-border)] bg-[var(--color-surface)] pt-[env(safe-area-inset-top)]"><div className="mx-auto flex min-h-14 w-full max-w-md items-center justify-between px-4"><div><p className="text-xs font-medium text-[var(--color-primary)]">MOBILE PROTOTYPE</p><h1 className="text-base font-semibold">{appName}</h1></div><button className="flex min-h-[44px] min-w-[44px] items-center justify-center rounded-[var(--radius-control)]"><PrototypeIcon name="settings" size={20} /></button></div></header><PrototypeState view={view}><main className="mx-auto max-w-md space-y-6 px-4 py-5 pb-24"><section className="rounded-[var(--radius-overlay)] bg-[var(--color-primary)] p-5 text-white"><StatusTag>Seed ready</StatusTag><h2 className="mt-4 text-2xl font-semibold">先验证产品，再建设系统。</h2><p className="mt-2 text-sm leading-6 text-white/80">用真实动线、状态和任务台账，把模糊需求迅速变成可以讨论的东西。</p><Button className="mt-5 bg-white text-[var(--color-primary-pressed)] active:bg-white/90">开始第一个场景</Button></section><Section title="快速验证"><div className="grid grid-cols-2 gap-3">{[["home","核心动线"],["modules","功能结构"],["profile","角色状态"],["info","异常状态"]].map(([icon,label]) => <Card key={label} className="flex min-h-28 flex-col justify-between"><PrototypeIcon name={icon as "home" | "modules" | "profile" | "info"} size={22} /><span className="text-sm font-medium">{label}</span></Card>)}</div></Section><Section title="下一步"><Card><p className="text-sm font-medium">填写 Product Brief</p><p className="mt-1 text-sm leading-6 text-[var(--color-text-secondary)]">然后在工作台账创建 T001，让 AI 从产品上下文开始施工。</p></Card></Section></main></PrototypeState><nav className="fixed inset-x-0 bottom-0 z-30 mx-auto flex min-h-16 max-w-md border-t border-[var(--color-border)] bg-[var(--color-surface)] pb-[env(safe-area-inset-bottom)]"><button className="flex flex-1 flex-col items-center justify-center gap-1 text-xs font-medium text-[var(--color-primary)]"><PrototypeIcon name="home" size={21} />首页</button><button className="flex flex-1 flex-col items-center justify-center gap-1 text-xs text-[var(--color-text-tertiary)]"><PrototypeIcon name="modules" size={21} />模块</button><button className="flex flex-1 flex-col items-center justify-center gap-1 text-xs text-[var(--color-text-tertiary)]"><PrototypeIcon name="profile" size={21} />我的</button></nav><PrototypePanel /></div>;
}
