import { Button, Card, Section, StatusTag } from "@prototype/design-system";
import { PrototypeIcon } from "@prototype/icons";
import { getPrototypeView, PrototypePanel, PrototypeState } from "@prototype/runtime";

const appName = import.meta.env.VITE_APP_NAME || "Com Design Prototype";

export function App() {
  const view = getPrototypeView();
  return <div className="flex min-h-screen bg-[var(--color-background)] text-[var(--color-text-primary)]"><aside className="hidden w-60 shrink-0 border-r border-[var(--color-border)] bg-[var(--color-surface)] p-4 md:block"><p className="text-xs font-semibold tracking-wide text-[var(--color-primary)]">PC PROTOTYPE</p><h1 className="mt-1 text-lg font-semibold">{appName}</h1><nav className="mt-8 space-y-1">{[["home","概览"],["modules","业务模块"],["profile","角色与用户"],["settings","配置"]].map(([icon,label],index) => <button key={label} className={`flex min-h-10 w-full items-center gap-3 rounded-[var(--radius-control)] px-3 text-sm ${index === 0 ? "bg-[var(--color-brand-subtle)] font-medium text-[var(--color-primary-pressed)]" : "text-[var(--color-text-secondary)] hover:bg-[var(--color-surface-subtle)]"}`}><PrototypeIcon name={icon as "home" | "modules" | "profile" | "settings"} size={18} />{label}</button>)}</nav></aside><div className="min-w-0 flex-1"><header className="flex min-h-16 items-center justify-between border-b border-[var(--color-border)] bg-[var(--color-surface)] px-5 md:px-8"><div><h2 className="font-semibold">产品验证工作台</h2><p className="text-xs text-[var(--color-text-tertiary)]">结构 · 状态 · 动线 · 决策</p></div><Button>新建验证场景</Button></header><PrototypeState view={view}><main className="mx-auto max-w-6xl space-y-7 p-5 md:p-8"><section className="grid gap-4 lg:grid-cols-[1.6fr_1fr]"><Card className="min-h-52 border-0 bg-[var(--color-primary)] p-6 text-white"><StatusTag>Seed ready</StatusTag><h2 className="mt-8 max-w-xl text-3xl font-semibold">把需求变成能点、能看、能争论的东西。</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/75">PC 与 Mobile 使用同一套产品事实与设计语义，但各自保持适合端侧的交互结构。</p></Card><Card className="p-6"><p className="text-sm font-medium">今天的验证闭环</p><ol className="mt-4 space-y-3 text-sm text-[var(--color-text-secondary)]"><li>1. Product Brief</li><li>2. T001 任务卡</li><li>3. 页面 + 状态</li><li>4. Review + 构建</li><li>5. 部署链接</li></ol></Card></section><Section title="验证维度"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{["核心动线","业务规则","角色权限","异常恢复"].map((label,index) => <Card key={label}><p className="text-xs text-[var(--color-text-tertiary)]">0{index + 1}</p><p className="mt-6 font-medium">{label}</p><p className="mt-2 text-sm leading-6 text-[var(--color-text-secondary)]">用 Prototype Runtime 切换状态并记录结论。</p></Card>)}</div></Section></main></PrototypeState></div><PrototypePanel /></div>;
}
